import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "We Up Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ // this is type sscript
  children: React.ReactNode; // this specifies the scope of the childen 
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2 className="bg-green-700 text-center text-2xl text-blue-900 decoration-white"> I AM A NAVBAE </h2>
        {children}
        </body>
    </html>
  );
}
