import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarDemo from "@/components/Navbar";
import { BackgroundGradientAnimation } from "@/components/ui/background-gradient-animation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "We Up Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ // this is type sscript
  children: React.ReactNode; // this specifies the scope of the childen 
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center">
        <NavbarDemo/>
        </div>
        <BackgroundGradientAnimation>
        {children}
        </BackgroundGradientAnimation>
        
        </body>
    </html>
  );
}